#!/usr/bin/env bash
# Loops 1 to 20 printing superstitious messages for specific numbers.
i=1
while [ "$i" -le 20 ]; do
  echo "$i"
  case $i in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac
  ((i++))
done
